#include "user_programs.h"
#include "string.h"
#include "fs/ramfs.h"

/* Symbols generated by objcopy from embedded ELF binaries */
extern const uint8_t _binary_hello_elf_start[];
extern const uint8_t _binary_hello_elf_end[];
extern const uint8_t _binary_counter_elf_start[];
extern const uint8_t _binary_counter_elf_end[];
extern const uint8_t _binary_fork_test_elf_start[];
extern const uint8_t _binary_fork_test_elf_end[];
extern const uint8_t _binary_cow_test_elf_start[];
extern const uint8_t _binary_cow_test_elf_end[];
extern const uint8_t _binary_multifork_test_elf_start[];
extern const uint8_t _binary_multifork_test_elf_end[];

static const struct user_program programs[] = {
    {
        .name = "hello",
        .data = _binary_hello_elf_start,
        .size = 0  /* computed at runtime */
    },
    {
        .name = "counter",
        .data = _binary_counter_elf_start,
        .size = 0
    },
    {
        .name = "fork_test",
        .data = _binary_fork_test_elf_start,
        .size = 0
    },
    {
        .name = "cow_test",
        .data = _binary_cow_test_elf_start,
        .size = 0
    },
    {
        .name = "multifork_test",
        .data = _binary_multifork_test_elf_start,
        .size = 0
    },
    { NULL, NULL, 0 }
};

static uint64_t program_size(const uint8_t *data) {
    if (data == _binary_hello_elf_start)
        return (uint64_t)(_binary_hello_elf_end - _binary_hello_elf_start);
    if (data == _binary_counter_elf_start)
        return (uint64_t)(_binary_counter_elf_end - _binary_counter_elf_start);
    if (data == _binary_fork_test_elf_start)
        return (uint64_t)(_binary_fork_test_elf_end - _binary_fork_test_elf_start);
    if (data == _binary_cow_test_elf_start)
        return (uint64_t)(_binary_cow_test_elf_end - _binary_cow_test_elf_start);
    if (data == _binary_multifork_test_elf_start)
        return (uint64_t)(_binary_multifork_test_elf_end - _binary_multifork_test_elf_start);
    return 0;
}

const struct user_program *user_programs_find(const char *name) {
    static struct user_program result;

    for (int i = 0; programs[i].name; i++) {
        if (strcmp(name, programs[i].name) == 0) {
            result.name = programs[i].name;
            result.data = programs[i].data;
            result.size = program_size(programs[i].data);
            return &result;
        }
    }
    return NULL;
}

void user_programs_populate_ramfs(void) {
    for (int i = 0; programs[i].name; i++) {
        ramfs_add_file(programs[i].name, programs[i].data,
                       program_size(programs[i].data));
    }
}
