#include "user_programs.h"
#include "string.h"
#include "fs/ramfs.h"

/* Symbols generated by objcopy from embedded ELF binaries */
extern const uint8_t _binary_hello_elf_start[];
extern const uint8_t _binary_hello_elf_end[];
extern const uint8_t _binary_counter_elf_start[];
extern const uint8_t _binary_counter_elf_end[];

static const struct user_program programs[] = {
    {
        .name = "hello",
        .data = _binary_hello_elf_start,
        .size = 0  /* computed at runtime */
    },
    {
        .name = "counter",
        .data = _binary_counter_elf_start,
        .size = 0
    },
    { NULL, NULL, 0 }
};

const struct user_program *user_programs_find(const char *name) {
    /* Use a static copy so we can fill in computed size */
    static struct user_program result;

    for (int i = 0; programs[i].name; i++) {
        if (strcmp(name, programs[i].name) == 0) {
            result.name = programs[i].name;
            result.data = programs[i].data;
            /* Compute size from linker symbols */
            if (programs[i].data == _binary_hello_elf_start)
                result.size = (uint64_t)(_binary_hello_elf_end - _binary_hello_elf_start);
            else if (programs[i].data == _binary_counter_elf_start)
                result.size = (uint64_t)(_binary_counter_elf_end - _binary_counter_elf_start);
            return &result;
        }
    }
    return NULL;
}

void user_programs_populate_ramfs(void) {
    for (int i = 0; programs[i].name; i++) {
        uint64_t size = 0;
        if (programs[i].data == _binary_hello_elf_start)
            size = (uint64_t)(_binary_hello_elf_end - _binary_hello_elf_start);
        else if (programs[i].data == _binary_counter_elf_start)
            size = (uint64_t)(_binary_counter_elf_end - _binary_counter_elf_start);

        ramfs_add_file(programs[i].name, programs[i].data, size);
    }
}
