#include "user_programs.h"
#include "string.h"
#include "fs/ramfs.h"

/* Symbols generated by objcopy from embedded ELF binaries */
extern const uint8_t _binary_hello_elf_start[];
extern const uint8_t _binary_hello_elf_end[];
extern const uint8_t _binary_counter_elf_start[];
extern const uint8_t _binary_counter_elf_end[];
extern const uint8_t _binary_fork_test_elf_start[];
extern const uint8_t _binary_fork_test_elf_end[];
extern const uint8_t _binary_cow_test_elf_start[];
extern const uint8_t _binary_cow_test_elf_end[];
extern const uint8_t _binary_multifork_test_elf_start[];
extern const uint8_t _binary_multifork_test_elf_end[];
extern const uint8_t _binary_pipe_test_elf_start[];
extern const uint8_t _binary_pipe_test_elf_end[];
extern const uint8_t _binary_signal_test_elf_start[];
extern const uint8_t _binary_signal_test_elf_end[];
extern const uint8_t _binary_procfs_test_elf_start[];
extern const uint8_t _binary_procfs_test_elf_end[];
extern const uint8_t _binary_echo_elf_start[];
extern const uint8_t _binary_echo_elf_end[];
extern const uint8_t _binary_ls_elf_start[];
extern const uint8_t _binary_ls_elf_end[];
extern const uint8_t _binary_ps_elf_start[];
extern const uint8_t _binary_ps_elf_end[];
extern const uint8_t _binary_mkdir_elf_start[];
extern const uint8_t _binary_mkdir_elf_end[];
extern const uint8_t _binary_touch_elf_start[];
extern const uint8_t _binary_touch_elf_end[];
extern const uint8_t _binary_rm_elf_start[];
extern const uint8_t _binary_rm_elf_end[];
extern const uint8_t _binary_net_test_elf_start[];
extern const uint8_t _binary_net_test_elf_end[];
extern const uint8_t _binary_nc_elf_start[];
extern const uint8_t _binary_nc_elf_end[];
extern const uint8_t _binary_httpd_elf_start[];
extern const uint8_t _binary_httpd_elf_end[];
extern const uint8_t _binary_ping_elf_start[];
extern const uint8_t _binary_ping_elf_end[];
extern const uint8_t _binary_exec_test_elf_start[];
extern const uint8_t _binary_exec_test_elf_end[];
extern const uint8_t _binary_waitpid_test_elf_start[];
extern const uint8_t _binary_waitpid_test_elf_end[];
extern const uint8_t _binary_argv_test_elf_start[];
extern const uint8_t _binary_argv_test_elf_end[];
extern const uint8_t _binary_fork_exec_test_elf_start[];
extern const uint8_t _binary_fork_exec_test_elf_end[];
extern const uint8_t _binary_mmap_test_elf_start[];
extern const uint8_t _binary_mmap_test_elf_end[];
extern const uint8_t _binary_epoll_test_elf_start[];
extern const uint8_t _binary_epoll_test_elf_end[];
extern const uint8_t _binary_cp_elf_start[];
extern const uint8_t _binary_cp_elf_end[];
extern const uint8_t _binary_mv_elf_start[];
extern const uint8_t _binary_mv_elf_end[];
extern const uint8_t _binary_df_elf_start[];
extern const uint8_t _binary_df_elf_end[];
extern const uint8_t _binary_grep_elf_start[];
extern const uint8_t _binary_grep_elf_end[];
extern const uint8_t _binary_head_elf_start[];
extern const uint8_t _binary_head_elf_end[];
extern const uint8_t _binary_tail_elf_start[];
extern const uint8_t _binary_tail_elf_end[];
extern const uint8_t _binary_top_elf_start[];
extern const uint8_t _binary_top_elf_end[];
extern const uint8_t _binary_kill_elf_start[];
extern const uint8_t _binary_kill_elf_end[];
extern const uint8_t _binary_ifconfig_elf_start[];
extern const uint8_t _binary_ifconfig_elf_end[];
extern const uint8_t _binary_netstat_elf_start[];
extern const uint8_t _binary_netstat_elf_end[];
extern const uint8_t _binary_sh_elf_start[];
extern const uint8_t _binary_sh_elf_end[];
extern const uint8_t _binary_id_elf_start[];
extern const uint8_t _binary_id_elf_end[];
extern const uint8_t _binary_whoami_elf_start[];
extern const uint8_t _binary_whoami_elf_end[];
extern const uint8_t _binary_demand_test_elf_start[];
extern const uint8_t _binary_demand_test_elf_end[];
extern const uint8_t _binary_perm_test_elf_start[];
extern const uint8_t _binary_perm_test_elf_end[];
extern const uint8_t _binary_nonblock_test_elf_start[];
extern const uint8_t _binary_nonblock_test_elf_end[];
extern const uint8_t _binary_wm_elf_start[];
extern const uint8_t _binary_wm_elf_end[];

static const struct user_program programs[] = {
    {
        .name = "hello",
        .data = _binary_hello_elf_start,
        .size = 0  /* computed at runtime */
    },
    {
        .name = "counter",
        .data = _binary_counter_elf_start,
        .size = 0
    },
    {
        .name = "fork_test",
        .data = _binary_fork_test_elf_start,
        .size = 0
    },
    {
        .name = "cow_test",
        .data = _binary_cow_test_elf_start,
        .size = 0
    },
    {
        .name = "multifork_test",
        .data = _binary_multifork_test_elf_start,
        .size = 0
    },
    {
        .name = "pipe_test",
        .data = _binary_pipe_test_elf_start,
        .size = 0
    },
    {
        .name = "signal_test",
        .data = _binary_signal_test_elf_start,
        .size = 0
    },
    {
        .name = "procfs_test",
        .data = _binary_procfs_test_elf_start,
        .size = 0
    },
    {
        .name = "echo",
        .data = _binary_echo_elf_start,
        .size = 0
    },
    {
        .name = "ls",
        .data = _binary_ls_elf_start,
        .size = 0
    },
    {
        .name = "ps",
        .data = _binary_ps_elf_start,
        .size = 0
    },
    {
        .name = "mkdir",
        .data = _binary_mkdir_elf_start,
        .size = 0
    },
    {
        .name = "touch",
        .data = _binary_touch_elf_start,
        .size = 0
    },
    {
        .name = "rm",
        .data = _binary_rm_elf_start,
        .size = 0
    },
    {
        .name = "net_test",
        .data = _binary_net_test_elf_start,
        .size = 0
    },
    {
        .name = "nc",
        .data = _binary_nc_elf_start,
        .size = 0
    },
    {
        .name = "httpd",
        .data = _binary_httpd_elf_start,
        .size = 0
    },
    {
        .name = "ping",
        .data = _binary_ping_elf_start,
        .size = 0
    },
    {
        .name = "exec_test",
        .data = _binary_exec_test_elf_start,
        .size = 0
    },
    {
        .name = "waitpid_test",
        .data = _binary_waitpid_test_elf_start,
        .size = 0
    },
    {
        .name = "argv_test",
        .data = _binary_argv_test_elf_start,
        .size = 0
    },
    {
        .name = "fork_exec_test",
        .data = _binary_fork_exec_test_elf_start,
        .size = 0
    },
    {
        .name = "mmap_test",
        .data = _binary_mmap_test_elf_start,
        .size = 0
    },
    {
        .name = "epoll_test",
        .data = _binary_epoll_test_elf_start,
        .size = 0
    },
    {
        .name = "cp",
        .data = _binary_cp_elf_start,
        .size = 0
    },
    {
        .name = "mv",
        .data = _binary_mv_elf_start,
        .size = 0
    },
    {
        .name = "df",
        .data = _binary_df_elf_start,
        .size = 0
    },
    {
        .name = "grep",
        .data = _binary_grep_elf_start,
        .size = 0
    },
    {
        .name = "head",
        .data = _binary_head_elf_start,
        .size = 0
    },
    {
        .name = "tail",
        .data = _binary_tail_elf_start,
        .size = 0
    },
    {
        .name = "top",
        .data = _binary_top_elf_start,
        .size = 0
    },
    {
        .name = "kill",
        .data = _binary_kill_elf_start,
        .size = 0
    },
    {
        .name = "ifconfig",
        .data = _binary_ifconfig_elf_start,
        .size = 0
    },
    {
        .name = "netstat",
        .data = _binary_netstat_elf_start,
        .size = 0
    },
    {
        .name = "sh",
        .data = _binary_sh_elf_start,
        .size = 0
    },
    {
        .name = "id",
        .data = _binary_id_elf_start,
        .size = 0
    },
    {
        .name = "whoami",
        .data = _binary_whoami_elf_start,
        .size = 0
    },
    {
        .name = "demand_test",
        .data = _binary_demand_test_elf_start,
        .size = 0
    },
    {
        .name = "perm_test",
        .data = _binary_perm_test_elf_start,
        .size = 0
    },
    {
        .name = "nonblock_test",
        .data = _binary_nonblock_test_elf_start,
        .size = 0
    },
    {
        .name = "wm",
        .data = _binary_wm_elf_start,
        .size = 0
    },
    { NULL, NULL, 0 }
};

static uint64_t program_size(const uint8_t *data) {
    if (data == _binary_hello_elf_start)
        return (uint64_t)(_binary_hello_elf_end - _binary_hello_elf_start);
    if (data == _binary_counter_elf_start)
        return (uint64_t)(_binary_counter_elf_end - _binary_counter_elf_start);
    if (data == _binary_fork_test_elf_start)
        return (uint64_t)(_binary_fork_test_elf_end - _binary_fork_test_elf_start);
    if (data == _binary_cow_test_elf_start)
        return (uint64_t)(_binary_cow_test_elf_end - _binary_cow_test_elf_start);
    if (data == _binary_multifork_test_elf_start)
        return (uint64_t)(_binary_multifork_test_elf_end - _binary_multifork_test_elf_start);
    if (data == _binary_pipe_test_elf_start)
        return (uint64_t)(_binary_pipe_test_elf_end - _binary_pipe_test_elf_start);
    if (data == _binary_signal_test_elf_start)
        return (uint64_t)(_binary_signal_test_elf_end - _binary_signal_test_elf_start);
    if (data == _binary_procfs_test_elf_start)
        return (uint64_t)(_binary_procfs_test_elf_end - _binary_procfs_test_elf_start);
    if (data == _binary_echo_elf_start)
        return (uint64_t)(_binary_echo_elf_end - _binary_echo_elf_start);
    if (data == _binary_ls_elf_start)
        return (uint64_t)(_binary_ls_elf_end - _binary_ls_elf_start);
    if (data == _binary_ps_elf_start)
        return (uint64_t)(_binary_ps_elf_end - _binary_ps_elf_start);
    if (data == _binary_mkdir_elf_start)
        return (uint64_t)(_binary_mkdir_elf_end - _binary_mkdir_elf_start);
    if (data == _binary_touch_elf_start)
        return (uint64_t)(_binary_touch_elf_end - _binary_touch_elf_start);
    if (data == _binary_rm_elf_start)
        return (uint64_t)(_binary_rm_elf_end - _binary_rm_elf_start);
    if (data == _binary_net_test_elf_start)
        return (uint64_t)(_binary_net_test_elf_end - _binary_net_test_elf_start);
    if (data == _binary_nc_elf_start)
        return (uint64_t)(_binary_nc_elf_end - _binary_nc_elf_start);
    if (data == _binary_httpd_elf_start)
        return (uint64_t)(_binary_httpd_elf_end - _binary_httpd_elf_start);
    if (data == _binary_ping_elf_start)
        return (uint64_t)(_binary_ping_elf_end - _binary_ping_elf_start);
    if (data == _binary_exec_test_elf_start)
        return (uint64_t)(_binary_exec_test_elf_end - _binary_exec_test_elf_start);
    if (data == _binary_waitpid_test_elf_start)
        return (uint64_t)(_binary_waitpid_test_elf_end - _binary_waitpid_test_elf_start);
    if (data == _binary_argv_test_elf_start)
        return (uint64_t)(_binary_argv_test_elf_end - _binary_argv_test_elf_start);
    if (data == _binary_fork_exec_test_elf_start)
        return (uint64_t)(_binary_fork_exec_test_elf_end - _binary_fork_exec_test_elf_start);
    if (data == _binary_mmap_test_elf_start)
        return (uint64_t)(_binary_mmap_test_elf_end - _binary_mmap_test_elf_start);
    if (data == _binary_epoll_test_elf_start)
        return (uint64_t)(_binary_epoll_test_elf_end - _binary_epoll_test_elf_start);
    if (data == _binary_cp_elf_start)
        return (uint64_t)(_binary_cp_elf_end - _binary_cp_elf_start);
    if (data == _binary_mv_elf_start)
        return (uint64_t)(_binary_mv_elf_end - _binary_mv_elf_start);
    if (data == _binary_df_elf_start)
        return (uint64_t)(_binary_df_elf_end - _binary_df_elf_start);
    if (data == _binary_grep_elf_start)
        return (uint64_t)(_binary_grep_elf_end - _binary_grep_elf_start);
    if (data == _binary_head_elf_start)
        return (uint64_t)(_binary_head_elf_end - _binary_head_elf_start);
    if (data == _binary_tail_elf_start)
        return (uint64_t)(_binary_tail_elf_end - _binary_tail_elf_start);
    if (data == _binary_top_elf_start)
        return (uint64_t)(_binary_top_elf_end - _binary_top_elf_start);
    if (data == _binary_kill_elf_start)
        return (uint64_t)(_binary_kill_elf_end - _binary_kill_elf_start);
    if (data == _binary_ifconfig_elf_start)
        return (uint64_t)(_binary_ifconfig_elf_end - _binary_ifconfig_elf_start);
    if (data == _binary_netstat_elf_start)
        return (uint64_t)(_binary_netstat_elf_end - _binary_netstat_elf_start);
    if (data == _binary_sh_elf_start)
        return (uint64_t)(_binary_sh_elf_end - _binary_sh_elf_start);
    if (data == _binary_id_elf_start)
        return (uint64_t)(_binary_id_elf_end - _binary_id_elf_start);
    if (data == _binary_whoami_elf_start)
        return (uint64_t)(_binary_whoami_elf_end - _binary_whoami_elf_start);
    if (data == _binary_demand_test_elf_start)
        return (uint64_t)(_binary_demand_test_elf_end - _binary_demand_test_elf_start);
    if (data == _binary_perm_test_elf_start)
        return (uint64_t)(_binary_perm_test_elf_end - _binary_perm_test_elf_start);
    if (data == _binary_nonblock_test_elf_start)
        return (uint64_t)(_binary_nonblock_test_elf_end - _binary_nonblock_test_elf_start);
    if (data == _binary_wm_elf_start)
        return (uint64_t)(_binary_wm_elf_end - _binary_wm_elf_start);
    return 0;
}

const struct user_program *user_programs_find(const char *name) {
    static struct user_program result;

    for (int i = 0; programs[i].name; i++) {
        if (strcmp(name, programs[i].name) == 0) {
            result.name = programs[i].name;
            result.data = programs[i].data;
            result.size = program_size(programs[i].data);
            return &result;
        }
    }
    return NULL;
}

void user_programs_populate_ramfs(void) {
    for (int i = 0; programs[i].name; i++) {
        ramfs_add_file(programs[i].name, programs[i].data,
                       program_size(programs[i].data));
    }
}
