/* Minimal hand-written config.h for the HobbyOS TCC port — normally
 * generated by TCC's own ./configure, which we don't run in this
 * freestanding cross-build. */
#define TCC_VERSION "0.9.27-hobbyos"
#define CONFIG_TCCDIR "/lib/tcc"
#define CONFIG_SYSROOT ""
#define CONFIG_TCC_CRT_PREFIX "/lib"
#define CONFIG_TCC_ELFINTERP "/lib/ld.so"
#define CONFIG_LDDIR "lib"
#define CONFIG_MULTIARCHDIR ""
#define TCC_TARGET_X86_64 1
#define CONFIG_TCC_ASM 1
